/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import com.ezware.dialog.task.CommandLink;
import com.ezware.dialog.task.TaskDialogs;
import com.ezware.dialog.task.TaskDialogsDemo;

/**
 *
 * @author Pablo
 */
public class JDialogosX extends javax.swing.JPanel {

    /**
     * Creates new form JDialogosX
     */
    public JDialogosX() {
        initComponents();
    
     
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultCommandLinkPainter1 = new com.ezware.dialog.task.design.DefaultCommandLinkPainter();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new JDialogosX().setVisible(true);
//                try {
//                   // UIManager.setLookAndFeel(new SubstanceBusinessBlueSteelLookAndFeel());
//
//                    //me gusta    UIManager.setLookAndFeel(new SubstanceCremeCoffeeLookAndFeel());
//                    //TaskPaneUI.createUI(new (TaskPaneUI)SubstanceCremeCoffeeLookAndFeel());
//                } catch (UnsupportedLookAndFeelException ex) {
//                    Logger.getLogger(FventanaIncial.class.getName()).log(Level.SEVERE, null, ex);
//                }

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ezware.dialog.task.design.DefaultCommandLinkPainter defaultCommandLinkPainter1;
    // End of variables declaration//GEN-END:variables
}
