/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import hibernate.anotaciones.util.JavaUtil;
import static hibernate.anotaciones.util.JavaUtil.setTableCellAlignment;
import hibernate.anotaciones.util.ObjectModelDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



public class Pinventario extends javax.swing.JPanel {

    private List resultList;
    private int pos;
    
    
    public Pinventario() {
//        this(0);
    }
    
//    public Pinventario(int tabCrud) {
//        initComponents();
//        
//        setTableCellAlignment(JLabel.CENTER,tablaConsultaMarca);
//        setTableCellAlignment(JLabel.CENTER,tablaModifMarca);
//        setTableCellAlignment(JLabel.CENTER,tablaDeletMarca);
//        
//        panelScrudMarca.setSelectedIndex(tabCrud);
//        
//        tablaModifMarca.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            public void valueChanged(ListSelectionEvent lse) {
//                if (!lse.getValueIsAdjusting()) {
//                    
//                    pos = tablaModifMarca.getSelectedRow();
//                    if (pos == -1) {
//                        return;
//                    }
//                    Marca m = (Marca) resultList.get(pos);
//                    nomb_a_Modf.setText(m.getNombre());
//                    idMarca.setText(m.getIdMarca().toString());
//                    
//                }
//            }
//        });
//        
//        tablaDeletMarca.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            public void valueChanged(ListSelectionEvent lse) {
//                if (!lse.getValueIsAdjusting()) {
//                    
//                    if (tablaDeletMarca.getSelectedRow() == -1) {
//                        return;
//                    }
//                    pos = tablaDeletMarca.getSelectedRow();
//                    
//                }
//            }
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        pnlRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAlmcen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonListarAlmacenes = new javax.swing.JButton();
        jButtonAceptarCabecera = new javax.swing.JButton();
        jButtonCancelarCabecera = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstatus = new javax.swing.JTextField();
        jButtonListarFacturas = new javax.swing.JButton();
        txtTrabajador = new javax.swing.JTextField();
        pnlListaRegistros = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtbulto = new javax.swing.JTextField();
        jButtonAgregarConteo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonListarProductos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDetalleRegistro = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSeleccionarTipoConsulta = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 600));

        pnlRegistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Almacen");

        txtAlmcen.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");

        jButtonListarAlmacenes.setText("+");
        jButtonListarAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarAlmacenesActionPerformed(evt);
            }
        });

        jButtonAceptarCabecera.setText("Aceptar");
        jButtonAceptarCabecera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarCabeceraActionPerformed(evt);
            }
        });

        jButtonCancelarCabecera.setText("Cancelar");
        jButtonCancelarCabecera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCabeceraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Factura");

        txtFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaActionPerformed(evt);
            }
        });

        jLabel8.setText("Por");

        txtEstatus.setEnabled(false);
        txtEstatus.setMinimumSize(new java.awt.Dimension(40, 22));

        jButtonListarFacturas.setText("+");
        jButtonListarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFacturasActionPerformed(evt);
            }
        });

        txtTrabajador.setEnabled(false);
        txtTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroLayout = new javax.swing.GroupLayout(pnlRegistro);
        pnlRegistro.setLayout(pnlRegistroLayout);
        pnlRegistroLayout.setHorizontalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTrabajador)
                    .addComponent(txtAlmcen))
                .addGap(40, 40, 40)
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonListarFacturas)
                    .addComponent(jButtonListarAlmacenes))
                .addGap(75, 75, 75)
                .addComponent(jButtonAceptarCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancelarCabecera)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        pnlRegistroLayout.setVerticalGroup(
            pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroLayout.createSequentialGroup()
                .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jButtonListarFacturas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlmcen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButtonListarAlmacenes)))
                    .addGroup(pnlRegistroLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(pnlRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAceptarCabecera)
                            .addComponent(jButtonCancelarCabecera))))
                .addGap(42, 42, 42))
        );

        jScrollPane4.setViewportView(pnlRegistro);

        pnlListaRegistros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        txtCodigo.setFocusCycleRoot(true);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        txtDescripcion.setEnabled(false);

        txtbulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbultoActionPerformed(evt);
            }
        });

        jButtonAgregarConteo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonAgregarConteo.setText("Agregar ");
        jButtonAgregarConteo.setEnabled(false);
        jButtonAgregarConteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarConteoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Producto");
        jLabel4.setEnabled(false);

        jButtonListarProductos.setText("+");
        jButtonListarProductos.setEnabled(false);
        jButtonListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProductosActionPerformed(evt);
            }
        });

        jTDetalleRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTDetalleRegistro.setCellSelectionEnabled(true);
        jTDetalleRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDetalleRegistroKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTDetalleRegistro);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad");
        jLabel6.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Descripcion:");
        jLabel1.setEnabled(false);

        jComboBoxSeleccionarTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Consulta por Referencia", "Consulta por Codigo sku" }));
        jComboBoxSeleccionarTipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSeleccionarTipoConsultaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Tipo de Codigo:");
        jLabel9.setEnabled(false);

        jLabel10.setText("Nro Bulto");
        jLabel10.setEnabled(false);

        javax.swing.GroupLayout pnlListaRegistrosLayout = new javax.swing.GroupLayout(pnlListaRegistros);
        pnlListaRegistros.setLayout(pnlListaRegistrosLayout);
        pnlListaRegistrosLayout.setHorizontalGroup(
            pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(7, 7, 7)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListarProductos))
                            .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbulto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAgregarConteo)))
                        .addGap(6, 6, 6)
                        .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel9))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion)
                            .addComponent(jComboBoxSeleccionarTipoConsulta, 0, 464, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlListaRegistrosLayout.setVerticalGroup(
            pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSeleccionarTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(txtbulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarConteo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlListaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(pnlListaRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarAlmacenesActionPerformed
        // ListarAlmacenes();

        //          try {
            //            JDListaAlmacenMiyake jdAlmacen = new JDListaAlmacenMiyake(this, true);
            //            jdAlmacen.setLocationRelativeTo(null);
            //            jdAlmacen.setVisible(true);
            //            if (jdAlmacen.almacen == null) {
                //                JOptionPane.showMessageDialog(this, "no ha Seleccionado Almacen");
                //            } else {
                //                al = jdAlmacen.almacen;
                //                this.txtAlmcen.setText(al.getNombre());
                //                //al.setIdAlmacen(3);
                //                System.err.println("Listar-Almacen-Obteniedo_id_alamacen :" + al.getIdAlmacen());
                //            }
            //        } catch (Exception ex) {
            //            JOptionPane.showMessageDialog(this, "Error al cargar Lista de Almacen" + ex);
            //        }
        //
        //
        //
    }//GEN-LAST:event_jButtonListarAlmacenesActionPerformed

    private void jButtonAceptarCabeceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarCabeceraActionPerformed

//        if (validar() == true) {
//            MetodoGenerales.activarControles3(pnlRegistro, false);
//            MetodoGenerales.activarControles3(pnlListaRegistros, true);
//        } else {
//            JOptionPane.showMessageDialog(this, "Faltan Datos");
//        }
    }//GEN-LAST:event_jButtonAceptarCabeceraActionPerformed

    private void jButtonCancelarCabeceraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCabeceraActionPerformed
//        al = null;
//        user = null;
//        this.txtAlmcen.setText("");
//        this.txtTrabajador.setText("");
    }//GEN-LAST:event_jButtonCancelarCabeceraActionPerformed

    private void txtFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaActionPerformed
        //   ValidarFactura();
    }//GEN-LAST:event_txtFacturaActionPerformed

    private void jButtonListarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFacturasActionPerformed

        try {
            JDFacturasPendientes jdFactura = new JDFacturasPendientes(null, true);
            jdFactura.setLocationRelativeTo(null);
            jdFactura.setVisible(true);
            if (jdFactura.factura == null) {
                JOptionPane.showMessageDialog(this, "no ha Seleccionado Facturas");
            } else {
//                fa = jdFactura.factura;
//                this.txtFactura.setText(fa.getIdFactura().toString());
//                this.txtEstatus.setText(fa.getRecibidoPor());

                //fa.setIdFactura(4);
                // this.txtAlmcen.setText(al.getNombre());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar Lista de Facturas" + ex);
        }

        //    ListarFacturas();
    }//GEN-LAST:event_jButtonListarFacturasActionPerformed

    private void txtTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrabajadorActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // ValidarCodigoBarra();
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        this.txtbulto.requestFocus();
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped

        char car = evt.getKeyChar();

        if ((car < '0' || car > '9')) {
            //  System.err.println("cacarter:*********+  -->" + car);
            evt.consume();
        }
        if (this.txtCantidad.getText().length() == 4) {
            evt.consume();
            // System.err.println("***************txtCantidadKeyTyped segundo 2º IF" + this.txtCantidad.getText());
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtbultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbultoActionPerformed
        try {
          //  AgregarConteo();
        } catch (Exception ex) {
            Logger.getLogger(PtomaFisica.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.txtCodigo.requestFocus();
    }//GEN-LAST:event_txtbultoActionPerformed

    private void jButtonAgregarConteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarConteoActionPerformed
        try {
           // AgregarConteo();
        } catch (Exception ex) {
            Logger.getLogger(PtomaFisica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAgregarConteoActionPerformed

    private void jButtonListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProductosActionPerformed
        //        try {
            //            if (jComboBoxSeleccionarTipoConsulta.getSelectedIndex() == 0) {
                //                //  MiyakeGestionAlmacen.cb = jComboBoxSeleccionarTipoConsulta;
                //                JDListaProductosEntradaProveedor jdProductosEP = new JDListaProductosEntradaProveedor(this, true);
                //                jdProductosEP.setVisible(true);
                //                if (jdProductosEP.proEP == null) {
                    //                    JOptionPane.showMessageDialog(this, "No ha Seleccioado Producto");
                    //                } else {
                    //                    proEP = jdProductosEP.proEP;
                    //                    //****************AQUI Dierecciona los valores****************
                    //                    this.txtCodigo.setText(proEP.getReferenciaProducto());
                    //                    this.txtDescripcion.setText(proEP.getDescripcionProducto());
                    //                    // this.txtCantidad.setFocusCycleRoot(rootPaneCheckingEnabled);
                    //                    this.txtCantidad.requestFocus();
                    //                    //    mta.fireTableDataChanged();
                    //                }
                //            } else {
                //                if (jComboBoxSeleccionarTipoConsulta.getSelectedIndex() == 1) {
                    //                    //    MiyakeGestionAlmacen.cb = jComboBoxSeleccionarTipoConsulta;
                    //                    JDListaProductosMiyake jdProductos = new JDListaProductosMiyake(this, true);
                    //                    jdProductos.setVisible(true);
                    //                    if (jdProductos.pro == null) {
                        //                        JOptionPane.showMessageDialog(this, "No ha Seleccioado Producto");
                        //                    } else {
                        //                        pro = jdProductos.pro;
                        //                        //****************AQUI Dierecciona los valores****************
                        //                        this.txtCodigo.setText(pro.getReferenciaProducto());
                        //                        this.txtDescripcion.setText(pro.getDescripcion());
                        //                        // this.txtCantidad.setFocusCycleRoot(rootPaneCheckingEnabled);
                        //                        this.txtCantidad.requestFocus();
                        //                        // mta.fireTableDataChanged();
                        //                    }
                    //                }
                //            }
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, "Error al cargar Lista de Trabajadores" + e);
            //        }
    }//GEN-LAST:event_jButtonListarProductosActionPerformed

    private void jTDetalleRegistroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDetalleRegistroKeyReleased
        //        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            //            if (JOptionPane.showConfirmDialog(this, "Desea eliminar el registro?",
                //                "Eliminar registro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            //            //se elimina
            //            int i;
            //            int[] selection = jTDetalleRegistro.getSelectedRows();
            //            for (i = 0; i < selection.length; i++) {
                //                selection[i] = jTDetalleRegistro.convertRowIndexToModel(selection[i]);
                //            }
            //            this.listaDetalle.remove(selection[i - 1]);
            //            mta.fireTableRowsDeleted(selection[0], selection[selection.length - 1]);
            //
            //        }
        //        }
    }//GEN-LAST:event_jTDetalleRegistroKeyReleased

    private void jComboBoxSeleccionarTipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSeleccionarTipoConsultaActionPerformed

        switch (jComboBoxSeleccionarTipoConsulta.getSelectedIndex()) {
            case 0:
            System.err.println("Seleccion Consultas por Referencia");
            //   MiyakeGestionAlmacen.cb = jComboBoxSeleccionarTipoConsulta;
            if (!this.txtCodigo.getText().isEmpty()) {

                break;
            } else {
                System.err.println("Entrado al NIDO");
                String codigo = this.txtCodigo.getText();
              //  EntradaProveedor referencia = null;
                try {
                    //  referencia = daoEntradaProveedor.comprobarReferenciaProducto(this.txtCodigo.getText());
                } catch (Exception ex) {
                    Logger.getLogger(PtomaFisica.class.getName()).log(Level.SEVERE, null, ex);
                }
//                if (codigo.equals(referencia)) {
//                    System.err.println("Macht-con-Dato de Entrada y Referencia Producto");
//                }

            }
            case 1:
            //  MiyakeGestionAlmacen.cb = jComboBoxSeleccionarTipoConsulta;
            System.err.println("Usted ha Seleccionado Consulta por Codigo sku");
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBoxSeleccionarTipoConsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptarCabecera;
    private javax.swing.JButton jButtonAgregarConteo;
    private javax.swing.JButton jButtonCancelarCabecera;
    private javax.swing.JButton jButtonListarAlmacenes;
    private javax.swing.JButton jButtonListarFacturas;
    private javax.swing.JButton jButtonListarProductos;
    private javax.swing.JComboBox jComboBoxSeleccionarTipoConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTDetalleRegistro;
    private javax.swing.JPanel pnlListaRegistros;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JTextField txtAlmcen;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstatus;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtTrabajador;
    private javax.swing.JTextField txtbulto;
    // End of variables declaration//GEN-END:variables
}
